repos:
  - repo: local
    hooks:
      - id: check-branch-and-files
        name: Check branch and modified files
        entry: './scripts/verify_branch.sh'
        language: script
        types: [file]
        pass_filenames: true
        always_run: true